# This is a basic workflow to help you get started with Actions

name: cocoa_diagnosis_keys

on:
  schedule:
    - cron:  '0 */4 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r ${{ github.workspace }}/opendata-converters/cocoa_diagnosis_keys/requirements.txt
      - name: Convert
        env:
          COCOA_DIAGNOSIS_KEYS_LIST_URL: ${{secrets.COCOA_DIAGNOSIS_KEYS_LIST_URL}}
          PYTHONPATH: cocoa_diagnosis_keys
        run: |
          cd ${{ github.workspace }}/opendata-converters/cocoa_diagnosis_keys
          python3 cocoa_diagnosis_keys.py --output_path ${{ github.workspace }}/output/v1/cocoa_diagnosis_keys/latest.csv
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: ${{ github.workspace }}/output
          clean: false
          git-config-name: cocoa-statistics
          git-config-email: noreply@keiji.dev
