# This is a basic workflow to help you get started with Actions

name: newly_confirmed_cases_daily

on:
  schedule:
    - cron:  '0 */6 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r ${{ github.workspace }}/opendata-converters/requirements.txt
      - name: Convert
        run: |
          cd ${{ github.workspace }}/opendata-converters
          python3 main.py --output_path ${{ github.workspace }}/output/v1/newly_confirmed_cases_daily/latest.csv
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ${{ github.workspace }}/output
          CLEAN: false
